### ISSUE TITLE
Create Home Page [3pt] - Student A

### ISSUE THREAD

**Issue by enoqueJonas** [enoqueJonas/tutoring-app-backend#2]
- On the main page, the user can see a [list of motorcycles/doctors/classes/items that you selected as a theme](https://www.behance.net/gallery/26425031/Vespa-Responsive-Redesign/modules/173005577).

![Image](https://github.com/enoqueJonas/tutoring-app-backend/assets/76396858/bbcdc378-729f-45ea-8d56-990210f9709f)

**Comment by jorgeabrahan** [comment]
Create home page:
https://github.com/enoqueJonas/tutoring-app-frontend/pull/3

Fetch class subjects from API and load them in home page
https://github.com/enoqueJonas/tutoring-app-frontend/pull/6
